
#ifndef _IMP_PEA_DETECTOR_COMMON_H_
#define _IMP_PEA_DETECTOR_COMMON_H_

#include "imp_pea_common.h"


#define IP_BGM_STA_INIT			0x10

#define IMP_BGM_STA_WORK			0x20

#define IMP_BGM_STA_SCENESTABLING	0x01

#define IMP_BGM_STA_SCENECHANGING	0x02

#define IMP_BGM_STA_SCENECHANGED	0x03

#define IMP_BGM_STA_MASK_MAIN		0xF0

#define IMP_BGM_STA_MASK_SUB		0x0F

#define IMP_BG_IS_INITING(x)			( (x&IMP_BGM_STA_MASK_MAIN)==IP_BGM_STA_INIT )

#define IMP_BG_IS_WORKING_NORMAL(x)		( (x&IMP_BGM_STA_MASK_MAIN)==IMP_BGM_STA_WORK && (x&IMP_BGM_STA_MASK_SUB)==0 )

#define IMP_BG_IS_WORKING_CHANGING(x)	( (x&IMP_BGM_STA_MASK_MAIN)==IMP_BGM_STA_WORK && (x&IMP_BGM_STA_MASK_SUB)==IMP_BGM_STA_SCENECHANGING )

#define IMP_BG_IS_WORKING_CHANGED(x)	( (x&IMP_BGM_STA_MASK_MAIN)==IMP_BGM_STA_WORK && (x&IMP_BGM_STA_MASK_SUB)==IMP_BGM_STA_SCENECHANGED )

typedef struct impPEA_DETECTOR_DATA_S
{
	IMP_S32 s32ThCurrent;
	IMP_S32 s32ThMax;
	IMP_S32 s32ThMin;
	IMP_U32 u32BgStatusCur;
	IMP_U32 u32BgStatusPre;
	IMP_S32 s32FgIsDiff;
	IMP_S32 s32Threshold;
	IMP_S32 s32BgInited;
	IMP_S32 s32PersonEnter;
	IMP_S32 s32PersonLeave;
	IMP_S32 s32LastPersonEnter;
	IMP_S32 s32EnterStartTime;
	GRAY_IMAGE_S *pstImgBgEdgeG;
} PEA_DETECTOR_DATA_S;



IMP_EXPORTS IMP_VOID IMP_PEA_DetectorDataClear( PEA_DETECTOR_DATA_S *pstData );


#endif
